# Generated by Django 6.0.8 on 2026-08-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-datetime']},
        ),
    ]
